<?php
/**
 * @file ax2.module
 *  XML-RPC server and XML-RPC client for Aegir XML-RPC Sign Up module.
 */

/**
 * Implementation of hook_menu().
 */
function ax2_menu() {
  $items = array();

  $items['admin/settings/ax2'] = array(
    'title' => t('Ax2: Aegir XML-RPC Sign Up'), 
    'description' => t('Configure settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ax2_admin_settings'),
    'access arguments' => array('administer ax'), 
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ax2.admin.inc', 
  );  

  return $items;
}

//-------------------------------
// xml-rpc server 
//-------------------------------

//-------------------------------
// xml-rpc client 
//-------------------------------

/**
 *  Get available platforms and corresponding node IDs.
 */
function ax2_get_platforms($key) {
  $valid_key = variable_get('ax2_api_key', FALSE);
  $url = variable_get('ax2_ax1_url', NULL); 
  $method = 'ax1.platforms'; 
  $result = xmlrpc($url, $method, $key); 

  return $result;
} 

/**
 * @return 
 *  List of available wildcard domains.
 */ 

/**
 * @param
 *  $domain, string, requested domain name. 
 * 
 * @return
 *  Status of requested domain.
 */

/**
 * Check to see if domain already exists.
 */
.
